### ISSUE TITLE
simple-git vulnerability on 1.1.0 version of @staticcms/proxy-server

### ISSUE THREAD

**Issue by r-angeles** [StaticJsCMS/static-cms-proxy-server#10]
Hi! Is a bumped version @staticcms/proxy-server with an updated simple-git (3.16.0) gonna be released? It seems the 3.15.0 version of the package is vulnerable. Here's the [link](https://github.com/advisories/GHSA-9w5j-4mwv-2wj8) of the advisory about the vulnerability.

**Comment by KaneFreeman** [comment]
`simple-git` has been removed as a dependency now.
